# Schema exploration and understanding the data

In [1]:
import polars as pl

In [2]:
# read schema of the data
schema = pl.read_excel(
    "/Users/thobelasixpence/Documents/de-projects/flight-performance-analytics-pipeline/data/ot_delaycause1_DL/Download_Column_Definitions.xlsx"
)

In [3]:
schema.head()

shape: (5, 2)
┌──────────────┬─────────────────────────────────┐
│ Column Name  ┆ Column Definition               │
│ ---          ┆ ---                             │
│ str          ┆ str                             │
╞══════════════╪═════════════════════════════════╡
│ year         ┆ YYYY format                     │
│ month        ┆ MM format (1-12)                │
│ carrier      ┆ Code assigned by assigned by U… │
│ carrier_name ┆ Unique airline (carrier) is de… │
│ airport      ┆ A three character alpha-numeri… │
└──────────────┴─────────────────────────────────┘

In [6]:
schema

shape: (21, 2)
┌─────────────────────┬─────────────────────────────────┐
│ Column Name         ┆ Column Definition               │
│ ---                 ┆ ---                             │
│ str                 ┆ str                             │
╞═════════════════════╪═════════════════════════════════╡
│ year                ┆ YYYY format                     │
│ month               ┆ MM format (1-12)                │
│ carrier             ┆ Code assigned by assigned by U… │
│ carrier_name        ┆ Unique airline (carrier) is de… │
│ airport             ┆ A three character alpha-numeri… │
│ …                   ┆ …                               │
│ carrier_delay       ┆ Carrier Delay, in Minutes       │
│ weather_delay       ┆ Weather Delay, in Minutes       │
│ nas_delay           ┆ National Air System Delay, in … │
│ security_delay      ┆ Security Delay, in Minutes      │
│ late_aircraft_delay ┆ Late Aircraft Delay, in Minute… │
└─────────────────────┴─────────────────────────────────┘